<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-OO0DI5VI" failures="1" tests="4" name="Test" time="8.638" errors="0" timestamp="2025-10-13T14:51:42 IST">
  <testcase classname="api.testcases.UserTest" name="testcreateUser" time="2.466"/>
  <testcase classname="api.testcases.UserTest" name="testgetUserData" time="1.167"/>
  <testcase classname="api.testcases.UserTest" name="testupdateUserData" time="2.236"/>
  <testcase classname="api.testcases.UserTest" name="testdeleteUserData" time="2.127">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.testcases.UserTest.testdeleteUserData(UserTest.java:88)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- testdeleteUserData -->
</testsuite> <!-- Test -->
